In [1]:
import torch

### 1 view 和 reshape

In [2]:
a = torch.rand(4, 1, 28, 28)

In [3]:
a.shape

torch.Size([4, 1, 28, 28])

In [4]:
# 相当于reshape
# 变换的要求：只要保证size不变就ok
a.view(4, 28*28)

tensor([[0.6353, 0.9277, 0.6567,  ..., 0.6900, 0.5952, 0.6692],
        [0.5572, 0.7358, 0.2827,  ..., 0.1159, 0.0972, 0.9723],
        [0.8536, 0.6874, 0.5966,  ..., 0.0940, 0.8718, 0.4173],
        [0.1804, 0.1278, 0.7997,  ..., 0.9401, 0.1464, 0.3966]])

In [5]:
a.view(4, 28*28).shape

torch.Size([4, 784])

### 2 Squeeze和unsqueeze

#### unsqueeze，取值范围是[-a.dim()-1, a.dim()+1)

In [6]:
a.shape

torch.Size([4, 1, 28, 28])

In [7]:
# 在第二个维度之后插入一个维度
a.unsqueeze(2).shape

torch.Size([4, 1, 1, 28, 28])

In [8]:
# 在第四个维度之后插入一个维度 
a.unsqueeze(4).shape

torch.Size([4, 1, 28, 28, 1])

刚开始，维度是1

In [9]:
a = torch.tensor([1.2, 2.1])
a.shape

torch.Size([2])

In [10]:
a

tensor([1.2000, 2.1000])

In [11]:
a.unsqueeze(0)

tensor([[1.2000, 2.1000]])

In [12]:
a.unsqueeze(0).shape

torch.Size([1, 2])

In [13]:
a.unsqueeze(-1)

tensor([[1.2000],
        [2.1000]])

In [14]:
a.unsqueeze(-1).shape

torch.Size([2, 1])

#### squeeze

In [15]:
b = torch.rand(1, 32, 1, 1)
b.shape

torch.Size([1, 32, 1, 1])

squeeze函数，如果对应维度是1，就会减少掉那个维度，如果不是1，就不会改变

In [16]:
b.squeeze().shape

torch.Size([32])

In [17]:
b.squeeze(0).shape

torch.Size([32, 1, 1])

In [18]:
b.squeeze(1).shape

torch.Size([1, 32, 1, 1])

### 3 Expand和Repeat

In [19]:
b.shape

torch.Size([1, 32, 1, 1])

In [20]:
b.expand(4, 32, 14, 14).shape

torch.Size([4, 32, 14, 14])

只有当从1变到其他维度时，1->n，才可行，如果是从n->m维，不可行

In [21]:
# -1表示不指定，由pytorch为你决定
b.expand(-1, 32, -1, -1).shape

torch.Size([1, 32, 1, 1])

#### repeat函数，传入的参数不是指维度，而是分别在每个维度上拷贝多少次

In [22]:
b.shape

torch.Size([1, 32, 1, 1])

In [23]:
# 如果要变成[4, 32, 28, 28]
b.repeat(4, 1, 28, 28).shape

torch.Size([4, 32, 28, 28])

### 4 转置操作

仅仅适用于矩阵

In [24]:
c = torch.rand(4, 3)
c

tensor([[0.3681, 0.7460, 0.9252],
        [0.3339, 0.8098, 0.3838],
        [0.5907, 0.8991, 0.5619],
        [0.1437, 0.0509, 0.0173]])

In [25]:
c.t()

tensor([[0.3681, 0.3339, 0.5907, 0.1437],
        [0.7460, 0.8098, 0.8991, 0.0509],
        [0.9252, 0.3838, 0.5619, 0.0173]])

#### transpose函数，维度交换

In [27]:
d = torch.rand(4, 3, 28, 28)

In [28]:
d.shape

torch.Size([4, 3, 28, 28])

In [29]:
d.transpose(0, 1).shape

torch.Size([3, 4, 28, 28])

#### permute 函数

In [30]:
# 参数就是想要的索引的组合
d.permute(1,0,2,3).shape

torch.Size([3, 4, 28, 28])