In [1]:
import torch

标量由只有一个元素的张量表示

In [2]:
x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x ** y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

可以将向量视为标量值组成的列表

In [3]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [4]:
x[3]

tensor(3)

In [5]:
len(x)

4

In [6]:
x.shape

torch.Size([4])

创建一个$m \times n$的矩阵

In [7]:
A = torch.arange(1,21).reshape(5, 4)
A

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]])

矩阵的转置

In [8]:
A.T

tensor([[ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19],
        [ 4,  8, 12, 16, 20]])

对称矩阵（symmetric matrix），$A=A^T$

In [9]:
B = torch.tensor([[1, 0, 0],[0, 1, 0],[0, 0, 1]])
B

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [10]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

可以使用`clone`方法将Tensor的一个副本赋值给新变量

In [11]:
C = B.clone()
C

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

两个矩阵的按元素的乘法称为 哈达玛积（Hadamard product），数学符号是$\odot$，注意和点乘的区别

In [12]:
# torch.eye() 可以创建一个对角矩阵
D = torch.eye(m=4, n=5)
A, D

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16],
         [17, 18, 19, 20]]),
 tensor([[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.],
         [0., 0., 0., 0.]]))

In [13]:
A * D

tensor([[ 1.,  0.,  0.,  0.],
        [ 0.,  6.,  0.,  0.],
        [ 0.,  0., 11.,  0.],
        [ 0.,  0.,  0., 16.],
        [ 0.,  0.,  0.,  0.]])

In [14]:
A + 2, A - 1, 2 * A, 1 / A, A**2

(tensor([[ 3,  4,  5,  6],
         [ 7,  8,  9, 10],
         [11, 12, 13, 14],
         [15, 16, 17, 18],
         [19, 20, 21, 22]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 2,  4,  6,  8],
         [10, 12, 14, 16],
         [18, 20, 22, 24],
         [26, 28, 30, 32],
         [34, 36, 38, 40]]),
 tensor([[1, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]),
 tensor([[  1,   4,   9,  16],
         [ 25,  36,  49,  64],
         [ 81, 100, 121, 144],
         [169, 196, 225, 256],
         [289, 324, 361, 400]]))

求和，计算元素的和

In [15]:
# 创建一个三维tensor
E = torch.arange(1,13, dtype=float).reshape([2, 3, 2])
E

tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]], dtype=torch.float64)

In [16]:
E.shape

torch.Size([2, 3, 2])

In [17]:
# 不指定参数
E.sum()

tensor(78., dtype=torch.float64)

In [18]:
E_sum_axis0 = E.sum(axis=0)
E_sum_axis0, E_sum_axis0.shape

(tensor([[ 8., 10.],
         [12., 14.],
         [16., 18.]], dtype=torch.float64),
 torch.Size([3, 2]))

In [19]:
E_sum_axis1 = E.sum(axis=1)
E_sum_axis1, E_sum_axis1.shape

(tensor([[ 9., 12.],
         [27., 30.]], dtype=torch.float64),
 torch.Size([2, 2]))

In [20]:
E_sum_axis2 = E.sum(axis=2)
E_sum_axis2, E_sum_axis2.shape

(tensor([[ 3.,  7., 11.],
         [15., 19., 23.]], dtype=torch.float64),
 torch.Size([2, 3]))

从上面我们可以看出，指定axis为哪个维度，就表示对应的维度变化，其他维度保持不变

In [21]:
# 指定为两个维度
E.sum(axis=[0, 1]), E.sum(axis=[0, 1]).shape

(tensor([36., 42.], dtype=torch.float64), torch.Size([2]))

In [22]:
# 注意这里和标量的区别
torch.tensor(2), torch.tensor(2).shape

(tensor(2), torch.Size([]))

In [23]:
# 也可以计算均值
E.mean(axis=0), E.mean(axis=0).shape


(tensor([[4., 5.],
         [6., 7.],
         [8., 9.]], dtype=torch.float64),
 torch.Size([3, 2]))

In [24]:
# 可以指定计算sum或均值时保持轴数不变
E.sum(axis=0), E.sum(axis=0, keepdims=True)

(tensor([[ 8., 10.],
         [12., 14.],
         [16., 18.]], dtype=torch.float64),
 tensor([[[ 8., 10.],
          [12., 14.],
          [16., 18.]]], dtype=torch.float64))

In [25]:
# 这样做的好处是在使用广播机制的时候，这时候维度就相同，可以广播
E/E.sum(axis=0, keepdims=True)

tensor([[[0.1250, 0.2000],
         [0.2500, 0.2857],
         [0.3125, 0.3333]],

        [[0.8750, 0.8000],
         [0.7500, 0.7143],
         [0.6875, 0.6667]]], dtype=torch.float64)

In [26]:
X = torch.arange(1,10, dtype=float).reshape(3,3)
A = torch.eye(3, dtype=float)
X, A

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]], dtype=torch.float64),
 tensor([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]], dtype=torch.float64))

In [27]:
# torch中的二维矩阵乘法
torch.mm(X,A), torch.mm(A,X)

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]], dtype=torch.float64),
 tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]], dtype=torch.float64))

In [28]:
# 向量的点积
v1 = torch.tensor([1,2,3,4])
v2 = torch.tensor([1,2,3,4])
torch.dot(v1, v2)

tensor(30)

计算范数

In [29]:
z = torch.tensor([3.0,4.0])
torch.norm(z)

tensor(5.)