### 1 从numpy数组导入

In [1]:
import torch
import numpy as np

In [2]:
# 创建一个numpy数组
a = np.array([2,3.3])
a

array([2. , 3.3])

In [3]:
# 从numpy导入数据
# 一维的tensor
torch.from_numpy(a)

tensor([2.0000, 3.3000], dtype=torch.float64)

In [4]:
b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
# 二维的tensor
torch.from_numpy(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

### 2 从List导入

In [6]:
torch.tensor([2, 3.2])

tensor([2.0000, 3.2000])

In [7]:
torch.tensor([[2, 3.2], [4.3, 5.6]])

tensor([[2.0000, 3.2000],
        [4.3000, 5.6000]])

In [8]:
# 传入一个shape
torch.Tensor(2, 3)
# 注意，这里的大写的tensor一般传入shape
# 小写的tensor一般传入一个数据

tensor([[0., 0., 0.],
        [0., 0., 0.]])

创建未初始化的tensor，不能直接使用，只是作为一个容器

In [9]:
torch.empty(1)

tensor([0.])

In [10]:
torch.IntTensor(2, 3)

tensor([[ 842293553, 1633760304,  892625718],
        [ 808740403,  858874164,  875848752]], dtype=torch.int32)

In [11]:
torch.FloatTensor(2, 3)

tensor([[1.3554e-05, 1.0187e-11, 2.5933e-09],
        [4.1724e-08, 8.3885e-07, 7.9959e+20]])

Tnesor表示的就是你设置的默认的数据类型

In [12]:
# 设置默认的数据类型
torch.set_default_tensor_type(torch.FloatTensor)


### 3 rand函数，生成随机数

In [13]:
# 产生的是[0,1)之间的随机数
torch.rand(1,4)

tensor([[0.3685, 0.5789, 0.3929, 0.3100]])

In [14]:
a = torch.Tensor(2, 3)

In [15]:
# 随机生成shape为a的一个张量
torch.rand_like(a)

tensor([[0.3882, 0.6376, 0.5642],
        [0.7812, 0.7298, 0.0994]])

In [16]:
# 可以看出，生成的随机数是[low, high)
torch.randint(0,1,(1,10))

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

生成随机正态分布的数

In [17]:
# randn函数，标准正态分布，均值为0，方差为1
torch.randn(2, 3)


tensor([[-0.7199,  0.2597, -0.7923],
        [-0.8353, -1.2044,  0.5904]])

In [18]:
# normal函数，离散正态分布，自定义均值和方差
torch.normal(mean=torch.full(size=[10], fill_value=0),
             std=torch.arange(1, 0, -0.1))

tensor([-1.7102,  0.1424, -0.4356, -0.5243, -0.3842,  0.2547,  0.3067,  0.0038,
        -0.1109,  0.0162])

### 4 其他的一些常用函数

full函数

In [19]:
# 生成一个标量
torch.full(size=[], fill_value=8)


tensor(8.)

In [20]:
# 生成一个向量
torch.full(size=[1], fill_value=8)


tensor([8.])

arange函数

In [21]:
# arange函数，参数：起始值，终止值，增量
torch.arange(0, 10, 1)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

linspace / logspace

In [22]:
# 在[0,10]区间内分4个点
torch.linspace(0, 10, steps=4)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [23]:
# 将0~-1之间分出10个点，对每个点分别取10的多少次方，如10^0, 10^-0.1...10^-1
torch.logspace(0, -1, steps=10)

tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])

ones/zeros/eye

In [24]:
# 生成4*4的单位矩阵
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

randperm函数

In [25]:
# 可以生成随机索引
# 如：生成从0~9的随机索引
torch.randperm(10)

tensor([9, 4, 1, 8, 5, 0, 7, 3, 6, 2])