In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.5'

In [5]:
import torch

In [6]:
torch.cuda.is_available()

True

In [7]:
t = torch.tensor([1,2,3])

In [8]:
t

tensor([1, 2, 3])

In [9]:
t.cuda()

tensor([1, 2, 3], device='cuda:0')

In [10]:
dd = torch.tensor([
    [1,2,3,4],
    [5,6,7,8]
])

In [11]:
dd.shape

torch.Size([2, 4])

In [12]:
dd.size()

torch.Size([2, 4])

In [13]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [14]:
torch.zeros([5,5])

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [15]:
torch.rand([2,2])

tensor([[0.8452, 0.8110],
        [0.1569, 0.6775]])

In [16]:
torch.randn([2,2])

tensor([[-1.6425, -0.8186],
        [ 0.2500, -0.5968]])

In [17]:
dd.reshape(1,8)

tensor([[1, 2, 3, 4, 5, 6, 7, 8]])

In [18]:
dd.reshape([4,2])

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [19]:
dd.flatten()

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
t = torch.arange(1,17).reshape([4,4])

In [21]:
t

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

In [22]:
t.numel()

16

In [23]:
t.max()

tensor(16)

In [25]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([4,5,6])
t3 = t1 > t2

In [26]:
t3

tensor([False, False, False])

In [27]:
t1[t3]

tensor([], dtype=torch.int64)

In [28]:
import torch
import torchvision
from torchvision import transforms

In [ ]:
train_set = torchvision.datasets.MNIST(
    root='./data',
    train=True,
    download=True,
    transform=transforms.Compose(
    )
)