In [1]:
import random

In [28]:
%%time
L = [random.randint(0,9) for i in range(1000)]
for i in range(len(L)):
    min_index = i
#     print('i={}, L={}'.format(i, L))
    for j in range(i+1,len(L)):
        if L[j] < L[min_index]:
            L[min_index], L[j] = L[j], L[min_index]
#             min_index = j
#     print('min={}, L={}'.format(L[min_index], L))
# print(L)

Wall time: 60.9 ms


In [73]:
def mergesort(L):
    if len(L) == 2:
        if L[0] > L[1]:
            L[0], L[1] = L[1], L[0]
        return L
    elif len(L) == 1:
        return L
    else:
        L_left = L[:int(len(L)/2)]
        L_left = mergesort(L_left)
        L_right = L[int(len(L)/2):]
        L_right = mergesort(L_right)
        L_new = []
        left_ind = 0
        right_ind = 0

        while(left_ind < len(L_left) and right_ind < len(L_right)):
            if L_left[left_ind] >= L_right[right_ind]:
                L_new.append(L_right[right_ind])
                right_ind += 1
            else:
                L_new.append(L_left[left_ind])
                left_ind += 1
        if left_ind >= len(L_left):
            for i in range(right_ind, len(L_right)):
                L_new.append(L_right[i])
        else:
            for i in range(left_ind, len(L_left)):
                L_new.append(L_left[i])
        return L_new

In [76]:
L = [random.randint(0,9) for i in range(10)]
print(L)
L = mergesort(L)
L

[3, 0, 9, 8, 8, 6, 6, 8, 5, 0]


[0, 0, 3, 5, 6, 6, 8, 8, 8, 9]

In [77]:
%%time
L = [random.randint(0,9) for i in range(1000)]
L = mergesort(L)

Wall time: 3.99 ms


In [1]:
import numpy as np

In [2]:
np.__version__

'1.17.3'

In [3]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
nparr.dtype

dtype('int32')

In [5]:
nparr.size

10

In [6]:
nparr.shape

(10,)

In [7]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

In [8]:
L = [1,2,3]

In [12]:
nparr2 = np.array(L)
nparr2

array([1, 2, 3])

In [13]:
nparr2[0] = 2
nparr2

array([2, 2, 3])

In [14]:
L

[1, 2, 3]

In [24]:
arr = np.full(shape=[4,4], fill_value=np.random.randint(10), dtype = 'float')
arr

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [28]:
for i in np.arange(10.5, 0, -0.5):
    print(i)

10.5
10.0
9.5
9.0
8.5
8.0
7.5
7.0
6.5
6.0
5.5
5.0
4.5
4.0
3.5
3.0
2.5
2.0
1.5
1.0
0.5


In [29]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [30]:
np.random.randint(9,13)

9

In [32]:
np.random.randint(1,10,size=[4,4])

array([[1, 9, 7, 3],
       [3, 9, 1, 3],
       [2, 6, 9, 5],
       [5, 6, 5, 2]])

In [33]:
np.random.random()

0.7387328142385476

In [35]:
np.random.random(size=[4,4])*100

array([[22.96536262, 23.39419863, 66.56604004, 15.91459869],
       [77.42509248, 90.4662322 ,  9.92339551, 87.87169883],
       [13.77764105, 72.37397807, 73.52370282, 55.30749673],
       [78.62641644, 77.20926949, 87.07528053, 62.68131768]])

In [36]:
np.random.normal(size=[4,4])

array([[-0.07568306,  0.02730189, -1.09640781,  0.54775004],
       [-0.76369045, -1.93966392,  1.0975246 ,  1.3819656 ],
       [ 0.26955061,  0.23033175,  0.78258603,  0.7018841 ],
       [-0.55992201,  0.67308891, -0.06445703,  1.33460366]])

In [38]:
np.random.randint(1,10,size=[10]).ndim

1

In [39]:
normalarr = np.random.normal(10,1,size=[4,4])
normalarr

array([[11.53286259, 10.24967103,  9.46682408,  9.12197076],
       [ 9.24914693, 10.00572461, 10.53140311,  9.66128994],
       [10.09355424, 10.51311654, 10.84603873,  9.63076375],
       [ 9.81646855, 10.35301343, 10.22415804,  9.80356021]])

In [41]:
normalarr[1][1]

10.005724608024561

In [42]:
normalarr[1,1]

10.005724608024561

In [43]:
X = np.random.randint(1,11,size=[3,5])
X

array([[ 9,  8,  5, 10,  2],
       [ 1,  8, 10,  2,  8],
       [ 6,  2,  3,  9,  2]])

In [44]:
X[:2, :2]

array([[9, 8],
       [1, 8]])

In [45]:
X[::-1]

array([[ 6,  2,  3,  9,  2],
       [ 1,  8, 10,  2,  8],
       [ 9,  8,  5, 10,  2]])

In [48]:
X[:,::-1]

array([[ 2, 10,  5,  8,  9],
       [ 8,  2, 10,  8,  1],
       [ 2,  9,  3,  2,  6]])

In [51]:
x = np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
data, label = np.split(x, [-1])
print(data)
print(label)

[1 2 3 4 5 6 7 8 9]
[10]


In [54]:
A = np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
A*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [56]:
1/A

D:\programs\Anaconda\envs\pytorch\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[       inf, 1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667, 0.14285714],
       [0.125     , 0.11111111, 0.1       , 0.09090909],
       [0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [57]:
A //2 

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5],
       [6, 6, 7, 7]], dtype=int32)

In [63]:
B = (A+1).copy()

In [64]:
B

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [65]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [66]:
A+B

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23],
       [25, 27, 29, 31]])

In [67]:
A-B

array([[-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

In [68]:
A*B

array([[  0,   2,   6,  12],
       [ 20,  30,  42,  56],
       [ 72,  90, 110, 132],
       [156, 182, 210, 240]])

In [69]:
A.dot(B)

array([[ 62,  68,  74,  80],
       [174, 196, 218, 240],
       [286, 324, 362, 400],
       [398, 452, 506, 560]])

In [71]:
I = np.identity(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [72]:
A.dot(I)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [73]:
np.linalg.inv(I)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [90]:
I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [91]:
I_1 = I[:, ::-1]
I_1

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

In [92]:
I.dot(I_1)

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

In [93]:
np.linalg.inv(I_1)

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

In [94]:
L = np.random.random(100)
L

array([0.63087903, 0.84554748, 0.07820845, 0.02203166, 0.88691827,
       0.60757578, 0.19521612, 0.56042147, 0.56685035, 0.87385782,
       0.58842306, 0.56534395, 0.46711337, 0.36891967, 0.44414614,
       0.38376285, 0.26037504, 0.9858578 , 0.26754519, 0.19510467,
       0.7144485 , 0.75912101, 0.03636543, 0.97600167, 0.98674321,
       0.70353464, 0.79672961, 0.31157176, 0.01125399, 0.16055913,
       0.12632606, 0.9414939 , 0.66327703, 0.41335013, 0.42184137,
       0.01903137, 0.36175212, 0.06948715, 0.22359893, 0.37187348,
       0.78302254, 0.42281459, 0.7177685 , 0.69987859, 0.10204945,
       0.07011595, 0.62980685, 0.08832757, 0.48885829, 0.434422  ,
       0.33162364, 0.26116133, 0.14165827, 0.6700042 , 0.29621013,
       0.1554015 , 0.44012561, 0.44182145, 0.88785374, 0.51948143,
       0.53397806, 0.36576343, 0.39722151, 0.30036   , 0.18027983,
       0.77730643, 0.73101311, 0.23094038, 0.18608366, 0.43064312,
       0.49504399, 0.70303764, 0.0775093 , 0.14338352, 0.94904

In [95]:
L.max()

0.9941291661929318

In [96]:
L.sum()

47.86973324855427

In [97]:
L.min()

0.01125398618945006

In [100]:
L = np.random.random(size=[2,4])
L

array([[0.00383084, 0.85936066, 0.98196716, 0.53328058],
       [0.74599628, 0.85181766, 0.95353719, 0.73661493]])

In [105]:
L.max(axis=0).reshape(4,-1)

array([[0.74599628],
       [0.85936066],
       [0.98196716],
       [0.73661493]])

In [106]:
L.var()

0.0884478714858618

In [108]:
L.std()

0.2974018686657194

In [109]:
L.argminx()

AttributeError: 'numpy.ndarray' object has no attribute 'argminx'

In [110]:
np.argmax(L)

2

In [113]:
x 

array([[0.00383084, 0.53328058, 0.98196716, 0.85936066],
       [0.73661493, 0.74599628, 0.95353719, 0.85181766]])